Feature advertisement service
geniusivanrozanov/CarsMarket pull request #6
Opened 2023-12-15 02:03 UTC by geniusivanrozanov

2023-12-17 20:30 UTC, katyalys requested changes

2023-12-17 20:30 UTC, katyalys commented on Services/IdentityService/IdentityService.Application/DataInitializers/IdentityDataInitializer.cs
> +        {
i guess you can remove loop from here

2023-12-17 20:30 UTC, katyalys commented on Services/IdentityService/IdentityService.Application/DataInitializers/IdentityDataInitializer.cs
> +                        $"Failed to create user with errors: {string.Join(", ", result.Errors.Select(e => e.Description))}");
define class with constants with exception messages

2023-12-17 20:30 UTC, katyalys commented on Services/Advertisement/Advertisement.Infrastructure/Data/Repositories/AdRepository.cs
> +    {
why dont you pass cancellation token to this method?

2023-12-17 20:30 UTC, katyalys commented on Services/Advertisement/Advertisement.Infrastructure/Data/Repositories/AdRepository.cs
> +    {
same

2023-12-27 12:33 UTC, geniusivanrozanov commented on Services/IdentityService/IdentityService.Application/DataInitializers/IdentityDataInitializer.cs
> +        {
Here i check the existence of all roles, that defined in constants

2023-12-27 12:44 UTC, geniusivanrozanov commented on Services/IdentityService/IdentityService.Application/DataInitializers/IdentityDataInitializer.cs
> +                        $"Failed to create user with errors: {string.Join(", ", result.Errors.Select(e => e.Description))}");
different messages are generated in different cases

2023-12-27 19:52 UTC, mebry requested changes

2023-12-27 19:52 UTC, mebry commented on Services/Advertisement/Advertisement.Application/Features/Commands/CreateAd/CreateAdCommandHandler.cs
For asynchronous methods, it's necessary to append Async to the end of the method name

2023-12-27 19:52 UTC, mebry commented on Services/Advertisement/Advertisement.Application/Features/Commands/DeleteAd/DeleteAdCommandHandler.cs
> +        await _adRepository.UpdateAd(entity, cancellationToken);
The same

2023-12-27 19:52 UTC, mebry commented on Services/Advertisement/Advertisement.WebAPI/Services/CurrentUser.cs
> +    public bool IsInRole(string role) => _user.IsInRole(role);
don't use =>. Instead, explicitly use curly braces, which will store the logic of the method, even if there is 1 line

2023-12-27 19:52 UTC, mebry commented on Services/IdentityService/IdentityService.Application/DataInitializers/IdentityDataInitializer.cs
> +                        $"Failed to create user with errors: {string.Join(", ", result.Errors.Select(e => e.Description))}");
Yes, you're right that you generate different text for different errors, but it says here that you need to create a separate class in which all messages will be stored so as not to write them explicitly here

2023-12-27 19:52 UTC, mebry commented on Services/Advertisement/Advertisement.WebAPI/Services/CurrentUser.cs
> +    public bool IsInRole(string role) => _user.IsInRole(role);
When describing a class, use the following structure:
· Declare all class members, including readonly or constants
· Declare all public properties, including auto-properties
· Declare all constructor(s)
· Declare the destructor, if any
· Declare all public methods
· Declare all protected methods
· Declare all private methods

2023-12-27 19:52 UTC, mebry commented on Services/IdentityService/IdentityService.Application/DataInitializers/IdentityDataInitializer.cs
> +        {
It makes sense

> Here i check the existence of all roles, that defined in constants

2023-12-27 20:33 UTC, mebry approved these changes

2023-12-27 20:40 UTC, merged